parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     reporting_tool
    database_user:     root
    database_password: ~

    mailer_transport:  
    mailer_host:       
    mailer_user:       
    mailer_password:   

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
