project_manager_project:
    resource: "@ProjectManagerProjectBundle/Resources/config/routing.yml"
    prefix:   /projectmanager/project

project_manager_parameter:
    resource: "@ProjectManagerParameterBundle/Resources/config/routing.yml"
    prefix:   /projectmanager/parameter

admin_customer:
    resource: "@AdminCustomerBundle/Resources/config/routing.yml"
    prefix:   /admin/customer

admin_component:
    resource: "@AdminComponentBundle/Resources/config/routing.yml"
    prefix:   /admin/component

admin_parameters:
    resource: "@AdminParametersBundle/Resources/config/routing.yml"
    prefix:   /admin/parameters

admin_role:
    resource: "@AdminRoleBundle/Resources/config/routing.yml"
    prefix:   /admin/role

admin_user:
    resource: "@AdminUserBundle/Resources/config/routing.yml"
    prefix:   /admin/user

admin_customer:
    resource: "@AdminCustomerBundle/Resources/config/routing.yml"
    prefix:   /admin/customer

