<?php

namespace ProjectManager\ParameterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PossibleValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PossibleValueRepository extends EntityRepository
{
}
